Feat/base entity 생성 #9
Wingle-SMWU/Wingle-Backend pull request #10
Opened 2023-01-26 07:46 UTC by LeeJE20

## ✅ 체크리스트
- [x] 테스트 코드가 잘 통과되나요?
- [x] 이 프로젝트의 코드 스타일을 따르나요?
- [ ] 문서변경이 필요한 경우, 변경하였나요?

## 📋 변경 유형
- [ ] Bug
- [x] Feature
- [ ] Breaking change (기존 기능을 변경하게 하는 bug 또는 feature)

## ✏️ PR 개요
- BaseEntity 생성
- CRUD 예제

resolved: #9

2023-01-29 03:50 UTC, yujin113 requested changes
저번에 논의했던 부분만 수정해서 다시 push해주시면 baseEntity 이용해서 다른 도메인도 만들겠습니다!
1. Reqeust -> RequestDto로 이름 변경
2. BaseEntity에 isDeleted 넣고 softDelete 메서드 생성

2023-01-29 12:54 UTC, gdakate approved these changes

2023-01-30 05:52 UTC, LeeJE20 commented
@yujin113 
soft delete 관련하여 delete 된 아이템 제외하고 읽어오는 부분도 자동으로 하려고 했는데 문제가 있어서 그냥 코드상에서 그때그때 delete된 아이템 제외하는 옵션을 추가해줘야 할 것 같습니다!

2023-01-30 13:37 UTC, yujin113 approved these changes

2023-01-31 09:48 UTC, merged