Feat/member 엔티티 생성 #12
Wingle-SMWU/Wingle-Backend pull request #17
Opened 2023-01-31 04:58 UTC by yujin113

## ✅ 체크리스트
- [ ] 테스트 코드가 잘 통과되나요?
- [x] 이 프로젝트의 코드 스타일을 따르나요?
- [ ] 문서변경이 필요한 경우, 변경하였나요?

## 📋 변경 유형
- [ ] Bug
- [x] Feature
- [ ] Breaking change (기존 기능을 변경하게 하는 bug 또는 feature)

## ✏️ PR 개요
- Member 엔티티 생성했습니다. 데이터베이스에 테이블 잘 생성된 것 확인했습니다.
<img width="700" alt="image" src="https://user-images.githubusercontent.com/73515587/215669261-6488c7c6-e4ea-4db2-9c82-21bbcd2e0c15.png">

- Permission 필드가 거절 0, 승인 1, 대기 2 값으로 들어가는데 코드 작성 시 헷갈릴 것 같아서 따로 enum을 만들었습니다. 테이블에는 int로 저장되며, Member 객체 생성할 때만 Permission.WAIT 이런 식으로 넣어주면 됩니다.
- 우선 Controller, Service, Repository 틀만 올렸습니다!

resolved: #12

2023-01-31 06:50 UTC, LeeJE20 requested changes

2023-01-31 06:50 UTC, LeeJE20 commented on wingle/src/main/java/kr/co/wingle/member/Member.java
> +	private int permission;
가급적 반영해 주세요!
제가 예전에 이렇게 @ColumnDefault만 설정하고 변수에 들어가는 값은 null로 했을 때 오류가 생긴 적 있었어요! DB에 들어갈 때 변수 값이 null이면 자동으로 디폴트 값이 들어가는 줄 알았는데 null은 넣을 수 없다는 오류가 나오더라고요. 
[여기 블로그 참고해주세요 ](https://velog.io/@xonic789/ColumnDefault-Springboot-JPA)
블로그에서는 @DynamicInsert 어노테이션 넣으면 된다고 나오긴 했는데, 저는 `private int permission = Permission.WAIT` 이런 식으로 해도 좋을 것 같습니다!

2023-01-31 11:48 UTC, LeeJE20 requested changes

2023-01-31 11:48 UTC, LeeJE20 commented on wingle/src/test/java/kr/co/wingle/member/MemberRepositoryTest.java
> +class MemberRepositoryTest {
가급적 반영해 주세요!
저희 1.9 회의할 때  repository는 테스트 안 해도 될 것 같다고 했어서 작성한 내용을 service안에 넣고, service를 테스트 하는 식으로 하면 더 좋을 것 같습니다!

2023-01-31 11:49 UTC, LeeJE20 commented on wingle/src/main/java/kr/co/wingle/member/Member.java
> +	private int permission;
반영해 주셔서 감사합니다! 수고하셨습니다~!

2023-02-01 01:19 UTC, yujin113 commented on wingle/src/test/java/kr/co/wingle/member/MemberRepositoryTest.java
> +class MemberRepositoryTest {
service에 들어갈 로직은 아닌 것 같아서 일단 RepositoryTest는 지웠습니다!

2023-02-02 05:05 UTC, yujin113 commented
약관 테이블, 약관 동의 이력 테이블 엔티티도 같이 생성했습니다.

2023-02-02 07:19 UTC, gdakate approved these changes

2023-02-02 15:13 UTC, LeeJE20 approved these changes
고생 많으셨습니다!!

2023-02-03 03:13 UTC, merged