gitignore  합치기
Wingle-SMWU/Wingle-Backend pull request #28
Opened 2023-02-04 05:21 UTC by KimRiun

## ✅ 체크리스트
- [x] 테스트 코드가 잘 통과되나요?
- [x] 이 프로젝트의 코드 스타일을 따르나요?
- [x] 문서변경이 필요한 경우, 변경하였나요?

## 📋 변경 유형
- [ ] Bug
- [x] Feature
- [ ] Breaking change (기존 기능을 변경하게 하는 bug 또는 feature)

## ✏️ PR 개요
- git ignore 파일이 2개로 나뉘어져있던 것을 최상단 gitignore로 합쳐 하나로 만들었습니다.

resolved: #26

2023-02-04 05:47 UTC, LeeJE20 commented on .gitignore
> +.idea
가급적 반영해주세요!
아래에도 .idea 있어서 여기는 지우는게 더 깔끔할 것 같아요

2023-02-04 05:49 UTC, LeeJE20 requested changes
꼼꼼하게 파일정리 해주셔서 감사드려요! 리뷰 남긴 부분도 한번 고려해주세요~

2023-02-04 05:49 UTC, LeeJE20 commented on .gitignore
> +.gradle
변경 요청합니다!
이건 build.gradle 파일도 제외하는건가요?
build.gradle 파일은 서로 공유하는것이 좋아 보여요!

2023-02-04 05:49 UTC, LeeJE20 commented on .gitignore
> +.idea
가급적 반영해주세요!
아래에도 .idea 있어서 여기는 지우는게 더 깔끔할 것 같아요

2023-02-11 08:56 UTC, KimRiun commented on .gitignore
> +.gradle
네 수정하였습니다!!

2023-02-11 08:57 UTC, KimRiun commented on .gitignore
> +.idea
네 수정하였습니다!!

2023-02-12 22:31 UTC, LeeJE20 approved these changes

2023-02-20 08:44 UTC, KimRiun commented on .gitignore
> +.gradle
wingle/.gradle/ 에 있는 파일들을 제외하는 것으로 build.gradle 파일은 추적하는 것으로 확인하였습니다. 따라서 gitignore에 .gradle를 추가하겠습니다!

2023-02-20 08:44 UTC, merged