Feat/ 인증 번호 전송하기 #44
Wingle-SMWU/Wingle-Backend pull request #45
Opened 2023-02-15 15:37 UTC by KimRiun

## ✅ 체크리스트
- [ ] 테스트 코드가 잘 통과되나요?
- [X] 이 프로젝트의 코드 스타일을 따르나요?
- [X] 문서변경이 필요한 경우, 변경하였나요?

## 📋 변경 유형
- [ ] Bug
- [X] Feature
- [ ] Breaking change (기존 기능을 변경하게 하는 bug 또는 feature)

## ✏️ PR 개요
- 사용자 이메일로 4자리 숫자(0~9) 인증번호를 전송하는 API를 구현하였습니다.
- 이메일 전송과 관련하여 application.yml 파일이 수정되었습니다.

resolved: #44

2023-02-15 15:59 UTC, yujin113 commented
Projects랑 Milestone도 지정해주세요!

2023-02-15 16:05 UTC, yujin113 reviewed
P3: 웬만하면 반영해주세요!
포스트맨으로 테스트한 결과도 같이 캡처해서 올려주시면 보기 편할 것 같아요~~

2023-02-15 16:05 UTC, yujin113 commented on wingle/src/main/java/kr/co/wingle/member/AuthService.java
> +	MailService mailService;
@RequiredArgsConstructor 붙여져 있어서 @Autowired 빼고 `private final MailService mailService;` 로 선언하면 자동으로 주입해주니까 이렇게 쓰는게 더 깔끔할 것 같아요!

2023-02-15 16:10 UTC, yujin113 commented
```
/home/runner/work/Wingle-Backend/Wingle-Backend/wingle/src/main/java/kr/co/wingle/common/constants/SuccessCode.java:18: error: enum constant not expected here
[27](https://github.com/Wingle-SMWU/Wingle-Backend/actions/runs/4185527509/jobs/7253399942#step:11:28)
	EMAIL_SEND_SUCCESS(OK, "이메일 인증코드 전송 성공");
```
이 부분 때문에 빌드가 실패하는데 확인해주실 수 있나요?

2023-02-15 16:11 UTC, yujin113 reviewed
이 부분 때문에 빌드 실패하는 것 같아요 수정해주세요!

2023-02-15 16:11 UTC, yujin113 commented on wingle/src/main/java/kr/co/wingle/common/constants/SuccessCode.java
>      TOKEN_REISSUE_SUCCESS(OK, "토큰 재발급 성공");
이 부분 `;` -> `,` 이렇게 수정해야 될 것 같습니다

2023-02-16 00:47 UTC, KimRiun commented on wingle/src/main/java/kr/co/wingle/member/AuthService.java
> +	MailService mailService;
네! 반영하겠습니다~!

2023-02-16 02:09 UTC, yujin113 commented
머지해도 될 것 같아요! 수고하셨습니다👍

2023-02-16 05:15 UTC, yujin113 requested changes

2023-02-16 05:15 UTC, yujin113 commented on wingle/src/main/java/kr/co/wingle/common/config/MailConfig.java
> +	private final long validTime = 60 * 3L; // 3분
제가 RedisUtil에 expireDuration을 milli 단위로 바꿔놔서 `1000 * 60 * 3L` 로 바꿔야 할 것 같아요!
(토큰 유효시간 단위가 milli여서 바꿨습니다)

2023-02-16 07:54 UTC, merged